### ISSUE TITLE
Module 8 Lab B Ex 2 Task Step 4

### ISSUE THREAD

**Issue by XtremeLabsSupport** [MicrosoftLearning/20773_Analyzing-Big-Data-with-Microsoft-R#10]
This could be due to my configuration, however it may be useful for students who encounter a similar issue. The table in hive was actually named sshuserroutedelays. To check for the name you can use SHOW TABLES; in the hive CLI.

**Comment by JohnPWSharp** [comment]
I have updated the  lab instructions
