### ISSUE TITLE
CAn not install dplyrXDF package

### ISSUE THREAD

**Issue by rlopezgarcia** [MicrosoftLearning/20773_Analyzing-Big-Data-with-Microsoft-R#3]
On lab for Module 2 Exercise 4, if you try to install dplyrXDF package with the instructions published,
devtools::install_github("RevolutionAnalytics/dplyrXdf")

it sends an error that it could not find the RLang dependency

You should install a previous versión in order to work:
devtools::install_github("RevolutionAnalytics/dplyrXdf@v0.9.2")

**Comment by ebfelix** [comment]
I am having issues in installing the following packages
install.packages("dplyr")
install.packages("devtools")
devtools::install_github("RevolutionAnalytics/dplyrXdf@v0.9.2")

I have the following error messages. Please help out...

unable to access index for repository  https://mran.revolutionanalytics.com/snapshot/2016-11-01/src/contrib/
cannot open URL https://mran.revolutionanalytics.com/snapshot/2016-11-01/src/contrib/PACKAGES
unable to access index for repository  https://mran.revolutionanalytics.com/snapshot/2016-11-01/bin/windows/contrib/3.3
cannot open URL https://mran.revolutionanalytics.com/snapshot/2016-11-01/bin/windows/contrib/PACKAGES

**Comment by JohnPWSharp** [comment]
We have updated the lab and demo instructions. This issue should no longer occur
